version: "3"


services:
  duen-trader:
    image: duen-trader:latest
    build:
      context: ./services/duenService
      dockerfile: ./Dockerfile
    environment: 
      RUSLAN_API_PORT: "3000"
      RUSLAN_API_HOST: "market-place"